spring:
    application:
        name: locataire
    datasource:
        url: jdbc:h2:mem:dbLocataire
        driverClassName: org.h2.Driver
        username: root
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console
server:
    port: 8082
    servlet:
        context-path: /locataire
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/



# Path: Projet_base_de_donnees/serveur-registre/src/main/resources/application.yml