spring:
    application:
        name: bienImmo # the name of our application
    datasource:
        url: jdbc:h2:mem:bienImmoDb
        driverClassName: org.h2.Driver
        username: root
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        queue:
            name: bienImmoQueue

server:
    port: 8081
    servlet:
        context-path: /bienImmo # the context path of our application

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka # the link to the eureka server