spring:
  application:
    name: bienImmobilier
server:
  servlet:
    context-path: /bienImmobilier
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/

datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: root
  password: 23610703
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
h2:
  console:
    enabled: true
    path: /h2-console